Add debug configuration provider
mesonbuild/vscode-meson pull request #61
Opened 2022-02-11 14:32 UTC by Ongy

Planned todo: Add the build task of the debugged executable as preLaunchTask to force a rebuild.

Shares the first commit with https://github.com/mesonbuild/vscode-meson/pull/57

supersedes https://github.com/mesonbuild/vscode-meson/pull/23 IMO

2022-02-11 15:27 UTC, Ongy commented
This fixes https://github.com/mesonbuild/vscode-meson/issues/21 btw.

2022-02-11 15:50 UTC, Ongy commented
Added the mentioned `preLaunchTask`. The operation to calculate the targets became a bit more expensive. If performance becomes an issue on large projects, this might be a point for caching, and then refresh with the test controller and explorer

2022-02-11 18:31 UTC, dcbaker requested changes

2022-02-11 18:31 UTC, dcbaker commented on src/configprovider.ts
> +        for (let target of executables) {
can this be `for (const target of executables) {`?

2022-02-11 18:31 UTC, dcbaker commented on src/configprovider.ts
> +            let targetName = await getTargetName(target)
This can be const as well, right?

2022-02-11 18:31 UTC, dcbaker commented on src/configprovider.ts
> +        var ret: vscode.DebugConfiguration[] = [];
The two using `let` could actually be `const`, and the `var` could be `let`, right?

2022-02-12 05:33 UTC, dcbaker approved these changes
Needs a rebase, but looks good. Thanks

2022-02-12 05:40 UTC, merged