Added meson-gcc problem matcher to get gcc builderrors in problem view
mesonbuild/vscode-meson pull request #82
Opened 2022-04-10 09:04 UTC by MadsAndreasen

2022-04-10 17:51 UTC, Ongy approved these changes
I've been wondering how hard this one is...

2022-04-12 16:54 UTC, dcbaker requested changes
This deserves an entry in the changelog, but otherwise looks great. Thanks!

2022-04-25 15:56 UTC, tristan957 commented
May want to squash the commit

2022-06-25 06:07 UTC, dcbaker approved these changes

2022-06-25 20:01 UTC, merged